name: benchmark pull requests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: bencherdev/bencher@main
      - name: Run benchmarks
        run: |
          bencher run \
          --project nickel \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --adapter criterion \
          --err \
          cargo bench --package nickel-lang-core --bench numeric
